"""Cross-fit calibration — leakage-safe calibrated OOF + C_final.

Design invariants (from SKILL calibration):
- Calibrator NEVER sees X; it only receives (oof_scores, y).
- C_final is trained on ALL (oof_scores, y) and is only used for inference.
- The calibrated OOF used for evaluation is produced via cross-fit
  (each fold's calibrator is trained on the *other* folds — no same-row leak).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import numpy.typing as npt

from lizyml.calibration.base import BaseCalibratorAdapter


@dataclass
class CalibrationResult:
    """Outcome of cross-fit calibration.

    Attributes:
        c_final: Calibrator trained on ALL (oof_scores, y).
            Used for inference only.
        calibrated_oof: Cross-fit calibrated OOF probabilities.
            Length equals ``n_samples``; same row ordering as ``oof_scores``.
            Used for evaluation — never produced by ``c_final``.
        method: Calibration method name.
        split_indices: Per-fold ``(train_idx, valid_idx)`` used in cross-fit.
            Stored for reproducibility / audit.  Same ordering as the folds
            that produced ``calibrated_oof``.
        fallback_fold_flags: Per-fold flag, same ordering as ``split_indices``.
            ``True`` when no calibrator could be fitted for that fold (no
            covered training data, or a single-class training fold) so its
            validation rows fall back to the **uncalibrated** OOF probabilities.
            Metric-honesty marker for H-0058's documented fallback (#218).
        n_fallback_rows: Total number of validation rows across all folds that
            received the uncalibrated fallback instead of ``c_final``-family
            calibrated probabilities (includes partial NaN-score rows inside an
            otherwise-calibrated fold). ``0`` in the common fully-calibrated case.
    """

    c_final: BaseCalibratorAdapter
    calibrated_oof: npt.NDArray[np.float64]
    method: str
    split_indices: list[tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]]]
    fallback_fold_flags: list[bool] = field(default_factory=list)
    n_fallback_rows: int = 0


def cross_fit_calibrate(
    oof_scores: npt.NDArray[np.float64],
    y: npt.NDArray[Any],
    calibrator_factory: Callable[[], BaseCalibratorAdapter],
    *,
    split_indices: list[tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]]],
    oof_pred: npt.NDArray[np.float64] | None = None,
) -> CalibrationResult:
    """Produce leakage-safe calibrated OOF scores and a C_final calibrator.

    For each fold:
    - Calibrator is fitted on (oof_scores[train_idx], y[train_idx]).
    - Calibrated probabilities are predicted for valid_idx rows.

    C_final is trained on ALL (oof_scores, y) and is only used for inference.

    Split generation is the caller's responsibility (H-0044).  This function
    only performs the cross-fit loop over the provided indices.

    Args:
        oof_scores: 1-D base-model OOF scores (n_samples,).
            Accepts probabilities or raw scores (logits).
            May contain NaN for structurally uncovered rows
            (e.g. TimeSeriesCV first period).
        y: 1-D binary ground-truth labels (n_samples,).
        calibrator_factory: Callable returning a fresh calibrator instance.
        split_indices: Pre-computed ``(train_idx, valid_idx)`` pairs.
            Generated by the appropriate splitter for the configured
            ``split.method``.
        oof_pred: 1-D OOF probabilities (n_samples,).  Used as fallback
            for folds where no covered training data exists (H-0058).
            When ``None``, falls back to ``oof_scores`` (identity).

    Returns:
        :class:`CalibrationResult` with ``c_final`` and ``calibrated_oof``.
    """
    calibrated_oof = np.full_like(oof_scores, np.nan, dtype=np.float64)
    fallback = oof_pred if oof_pred is not None else oof_scores
    # Metric-honesty markers (#218): per-fold "no calibrator fitted" flags and
    # a total count of validation rows that received the uncalibrated fallback.
    fallback_fold_flags: list[bool] = []
    n_fallback_rows = 0

    for train_idx, val_idx in split_indices:
        # Skip structurally uncovered rows (NaN OOF scores) from
        # calibrator training.  With H-0058 (outer splits reused),
        # TimeSeriesCV train_idx may include first-period rows that
        # were never in any validation fold and thus have NaN scores.
        train_scores = oof_scores[train_idx]
        train_y = y[train_idx]
        finite_mask = ~np.isnan(train_scores)
        if not finite_mask.any():
            # No covered training data for this fold (e.g. TimeSeriesCV
            # fold 0 where all train rows are uncovered).  Use OOF
            # probabilities as-is (no calibration applied).
            calibrated_oof[val_idx] = fallback[val_idx]
            fallback_fold_flags.append(True)
            n_fallback_rows += len(val_idx)
            continue
        if np.unique(train_y[finite_mask]).size < 2:
            # Single-class training fold — a calibrator (e.g. Platt's
            # LogisticRegression) cannot fit on one class.  Fall back to the
            # uncalibrated OOF probabilities for this fold's validation rows
            # rather than letting an opaque sklearn ValueError escape.
            calibrated_oof[val_idx] = fallback[val_idx]
            fallback_fold_flags.append(True)
            n_fallback_rows += len(val_idx)
            continue
        cal = calibrator_factory()
        cal.fit(train_scores[finite_mask], train_y[finite_mask])
        fallback_fold_flags.append(False)

        # Guard: val_idx may include structurally uncovered rows (NaN OOF)
        # if calibration splits differ from outer CV splits in future.
        val_scores = oof_scores[val_idx]
        val_finite = ~np.isnan(val_scores)
        if val_finite.all():
            calibrated_oof[val_idx] = cal.predict(val_scores)
        elif val_finite.any():
            calibrated_oof[val_idx[val_finite]] = cal.predict(val_scores[val_finite])
            calibrated_oof[val_idx[~val_finite]] = fallback[val_idx[~val_finite]]
            n_fallback_rows += int((~val_finite).sum())
        else:
            # All val rows are NaN — use fallback entirely
            calibrated_oof[val_idx] = fallback[val_idx]
            n_fallback_rows += len(val_idx)

    # C_final: trained on ALL covered data — for inference only
    c_final = calibrator_factory()
    covered = ~np.isnan(oof_scores)
    c_final.fit(oof_scores[covered], y[covered])

    return CalibrationResult(
        c_final=c_final,
        calibrated_oof=calibrated_oof,
        method=c_final.name,
        split_indices=split_indices,
        fallback_fold_flags=fallback_fold_flags,
        n_fallback_rows=n_fallback_rows,
    )
