#!/usr/bin/env python3
"""PR 9: render the clause inventory (results/pr9_inventory_{A,B}.json) as a report.

The two JSON files are the scouts' per-clause verdicts against BLUEPRINT.md at
``13fb9d7``. This script derives every count in ``results/pr9_clause_inventory.md``
from them, so the report cannot drift from the data (DC3): re-run it after any
verdict changes and commit both.

Usage (from the repository root)::

    python3 docs/audits/2026-09-defect-discovery/instruments/pr9_inventory_report.py \
        > docs/audits/2026-09-defect-discovery/results/pr9_clause_inventory.md
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "results"
BATCHES = ("A", "B")
VERDICTS = ("stated", "missed", "contradicted", "superseded", "not_in_force", "off_surface")
OWED = ("missed", "contradicted")


def section_key(raw: str | None) -> str:
    """``## 15.2 互換性`` and ``15.2 互換性`` are one section; unknown stays visible."""
    if not raw:
        return "(no target section)"
    text = raw.lstrip("#").strip()
    match = re.match(r"(\d+(?:\.\d+)*)", text)
    return match.group(1) if match else text


def load() -> dict[str, dict]:
    entries: dict[str, dict] = {}
    for batch in BATCHES:
        data = json.loads((RESULTS / f"pr9_inventory_{batch}.json").read_text(encoding="utf-8"))
        if data.get("head") != "13fb9d7":
            raise SystemExit(f"batch {batch}: head {data.get('head')!r} is not 13fb9d7")
        for pid, entry in data["entries"].items():
            if pid in entries:
                raise SystemExit(f"{pid} appears in more than one batch")
            if "error" in entry:
                raise SystemExit(f"{pid}: scout reported an error: {entry['error']}")
            for clause in entry["clauses"]:
                if clause["verdict"] not in VERDICTS:
                    raise SystemExit(f"{pid}: unknown verdict {clause['verdict']!r}")
            entries[pid] = {**entry, "batch": batch}
    return entries


def main() -> int:
    entries = load()
    totals: Counter[str] = Counter()
    owed_by_section: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    names: dict[str, str] = {}
    out = sys.stdout
    for pid in sorted(entries):
        for clause in entries[pid]["clauses"]:
            totals[clause["verdict"]] += 1
            if clause["verdict"] in OWED:
                key = section_key(clause.get("target_section"))
                names.setdefault(key, clause.get("target_section") or key)
                owed_by_section[key].append((pid, clause))
    owing = sorted(
        pid for pid, e in entries.items()
        if any(c["verdict"] in OWED for c in e["clauses"])
    )
    print("# PR 9 — clause inventory against BLUEPRINT.md at 13fb9d7", file=out)
    print(file=out)
    print("Generated by `instruments/pr9_inventory_report.py` from "
          "`results/pr9_inventory_A.json` and `results/pr9_inventory_B.json`. "
          "Do not edit by hand.", file=out)
    print(file=out)
    print(f"- entries: {len(entries)}; clauses: {sum(totals.values())}", file=out)
    print("- " + " / ".join(f"{v} {totals[v]}" for v in VERDICTS), file=out)
    print(f"- entries owing a BLUEPRINT edit (any missed or contradicted clause): "
          f"{len(owing)}", file=out)
    print(f"- owed clauses: {sum(totals[v] for v in OWED)} in "
          f"{len(owed_by_section)} BLUEPRINT sections", file=out)
    print(file=out)
    print("## Per entry", file=out)
    print(file=out)
    print("| id | batch | clauses | " + " | ".join(VERDICTS) + " |", file=out)
    print("|---|---|---|" + "---|" * len(VERDICTS), file=out)
    for pid in sorted(entries):
        counts = Counter(c["verdict"] for c in entries[pid]["clauses"])
        print(f"| {pid} | {entries[pid]['batch']} | {len(entries[pid]['clauses'])} | "
              + " | ".join(str(counts[v]) for v in VERDICTS) + " |", file=out)
    print(file=out)
    print("## Owed clauses by BLUEPRINT section", file=out)
    for key in sorted(owed_by_section, key=lambda k: [int(p) if p.isdigit() else 0
                                                       for p in k.split(".")]):
        print(file=out)
        print(f"### {names[key]}", file=out)
        print(file=out)
        for pid, clause in owed_by_section[key]:
            lines = clause.get("blueprint_lines") or []
            where = f" (BLUEPRINT {lines[0]})" if lines else ""
            print(f"- **{pid}** `{clause['verdict']}`{where}: {clause['text']} "
                  f"— code `{clause.get('code') or '-'}`", file=out)
    other = [(pid, c) for pid in sorted(entries) for c in entries[pid]["clauses"]
             if c["verdict"] == "not_in_force"]
    print(file=out)
    print("## not_in_force (BLUEPRINT is not edited; filed as an issue)", file=out)
    print(file=out)
    for pid, clause in other:
        print(f"- **{pid}**: {clause['text']} — code `{clause.get('code') or '-'}`; "
              f"{clause.get('note') or ''}", file=out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
