"""templates — train.py and predict.py source code for codegen export."""

from __future__ import annotations

_TRAIN_PY = '''\
#!/usr/bin/env python3
"""Train a LightGBM model and fit a probability calibrator.

Usage:
    python train.py train_data.csv
    python train.py train_data.parquet --no-calibration

Steps:
    1. Fit feature pipeline (learn category mappings -> pipeline_state.json)
    2. Train LightGBM on full data (-> model.txt)
    3. Generate OOF scores via CV for calibration
    4. Fit calibrator on OOF scores (-> calibrator.json)

Generated by lizyml -- https://github.com/nbx-liz/LizyML
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import sys
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import (
    GroupKFold,
    KFold,
    StratifiedGroupKFold,
    StratifiedKFold,
    TimeSeriesSplit,
)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s  %(message)s", datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

ROOT = Path(__file__).parent
ARTIFACTS = ROOT / "artifacts"

with open(ROOT / "config.json", encoding="utf-8") as _f:
    CFG = json.load(_f)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Feature Pipeline
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def fit_pipeline(df: pd.DataFrame) -> dict:
    """Learn category mappings and save pipeline state."""
    expected = CFG["feature_names"]
    missing = sorted(set(expected) - set(df.columns))
    if missing:
        raise ValueError(f"Missing columns: {missing}")

    mappings: dict[str, dict[str, int]] = {}
    for col in CFG["categorical_features"]:
        cats = sorted(str(v) for v in df[col].dropna().unique())
        mappings[col] = {v: i for i, v in enumerate(cats)}
        log.info("    %s: %d categories", col, len(cats))

    state = {
        "feature_names": expected,
        "categorical_features": CFG["categorical_features"],
        "category_mappings": mappings,
    }
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    with open(ARTIFACTS / "pipeline_state.json", "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)
    return state


def transform(df: pd.DataFrame, state: dict) -> pd.DataFrame:
    """Apply fitted pipeline to a DataFrame."""
    X = df[state["feature_names"]].copy()
    for col, mapping in state.get("category_mappings", {}).items():
        if col in X.columns:
            X[col] = X[col].astype(str).map(mapping)  # unseen -> NaN
    return X


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  LightGBM Training
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def train_lgbm(X: pd.DataFrame, y: pd.Series, cat_cols: list[str]) -> lgb.Booster:
    """Train LightGBM with optional early stopping via holdout."""
    ds_full = lgb.Dataset(X, label=y, categorical_feature=cat_cols or "auto")
    callbacks: list = [lgb.log_evaluation(period=200)]
    train_set = ds_full
    valid_sets, valid_names = [ds_full], ["train"]

    ratio = CFG.get("validation_ratio", 0)
    es_rounds = CFG.get("early_stopping_rounds")
    if ratio > 0 and es_rounds:
        n = len(y)
        rng = np.random.default_rng(CFG["seed"])
        idx = rng.permutation(n)
        n_val = max(1, int(n * ratio))

        train_set = lgb.Dataset(
            X.iloc[idx[n_val:]], label=y.iloc[idx[n_val:]],
            categorical_feature=cat_cols or "auto",
        )
        valid_ds = lgb.Dataset(
            X.iloc[idx[:n_val]], label=y.iloc[idx[:n_val]],
            reference=train_set,
        )
        valid_sets = [train_set, valid_ds]
        valid_names = ["train", "valid"]
        callbacks.insert(0, lgb.early_stopping(es_rounds, verbose=True))
        log.info("    holdout: %d train / %d valid", n - n_val, n_val)

    fevals = build_feval_from_config()
    booster = lgb.train(
        CFG["lgbm_params"], train_set,
        num_boost_round=CFG["num_boost_round"],
        valid_sets=valid_sets, valid_names=valid_names,
        feval=fevals if fevals else None,
        callbacks=callbacks,
    )
    booster.save_model(str(ARTIFACTS / "model.txt"))
    log.info("    saved model.txt (best_iteration=%d)", booster.best_iteration)
    return booster


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Calibration
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _sigmoid(x: np.ndarray) -> np.ndarray:
    return np.where(x >= 0, 1 / (1 + np.exp(-x)), np.exp(x) / (1 + np.exp(x)))


def _softmax(x: np.ndarray) -> np.ndarray:
    """Row-wise softmax for 2D array."""
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Custom feval metrics (H-0066)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _feval_rmsle(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.sqrt(np.mean((np.log1p(y_true) - np.log1p(y_pred)) ** 2)))

def _feval_r2(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    if ss_tot == 0.0:
        return 1.0 if ss_res == 0.0 else 0.0
    return 1.0 - ss_res / ss_tot

def _feval_f1(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    from sklearn.metrics import f1_score
    pred = (y_pred >= 0.5).astype(int) if y_pred.dtype.kind == "f" else y_pred
    average = "binary" if len(np.unique(y_true)) == 2 else "macro"
    return float(f1_score(y_true, pred, zero_division=0, average=average))

def _feval_brier(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    if y_pred.ndim == 2:
        from sklearn.preprocessing import label_binarize
        from sklearn.metrics import brier_score_loss
        classes = np.arange(y_pred.shape[1])
        y_bin = label_binarize(y_true, classes=classes)
        per_class = [
            float(brier_score_loss(y_bin[:, k], y_pred[:, k]))
            for k in range(y_pred.shape[1])
        ]
        return float(np.mean(per_class))
    from sklearn.metrics import brier_score_loss
    return float(brier_score_loss(y_true, y_pred))

def _feval_ece(y_true: np.ndarray, y_pred: np.ndarray, *, n_bins: int = 10) -> float:
    bin_edges = np.linspace(0.0, 1.0, n_bins + 1)
    n = len(y_true)
    ece = 0.0
    for lo, hi in zip(bin_edges[:-1], bin_edges[1:], strict=True):
        mask = (y_pred >= lo) & (y_pred <= hi if hi == 1.0 else y_pred < hi)
        if not mask.any():
            continue
        acc = float(np.mean(y_true[mask]))
        conf = float(np.mean(y_pred[mask]))
        ece += (mask.sum() / n) * abs(acc - conf)
    return ece

def _feval_precision_at_k(
    y_true: np.ndarray, y_pred: np.ndarray, *, k: int = 10,
) -> float:
    n = len(y_true)
    n_top = max(1, int(n * k / 100))
    top_idx = np.argsort(y_pred)[::-1][:n_top]
    return float(np.mean(y_true[top_idx]))

def _feval_accuracy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    from sklearn.metrics import accuracy_score
    pred = (y_pred >= 0.5).astype(int) if y_pred.dtype.kind == "f" else y_pred
    return float(accuracy_score(y_true, pred))

def _feval_smape(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = np.abs(y_true) + np.abs(y_pred)
    with np.errstate(divide="ignore", invalid="ignore"):
        terms = np.where(denom == 0, 0.0, 2.0 * np.abs(y_true - y_pred) / denom)
    return float(np.mean(terms) * 100.0)

def _feval_wape(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = float(np.sum(np.abs(y_true)))
    if denom == 0.0:
        raise ValueError("WAPE is undefined when sum(|y_true|) is zero.")
    return float(np.sum(np.abs(y_true - y_pred)) / denom * 100.0)


_FEVAL_REGISTRY: dict = {
    "rmsle": _feval_rmsle,
    "r2": _feval_r2,
    "f1": _feval_f1,
    "brier": _feval_brier,
    "ece": _feval_ece,
    "precision_at_k": _feval_precision_at_k,
    "accuracy": _feval_accuracy,
    "smape": _feval_smape,
    "wape": _feval_wape,
}


def build_feval_from_config() -> list:
    """Build LightGBM feval callables from config.json feval_metrics."""
    feval_entries = CFG.get("feval_metrics", [])
    if not feval_entries:
        return []

    task = CFG["_task"]
    fevals: list = []
    for entry in feval_entries:
        name = entry["name"]
        params = entry.get("params", {})
        greater_is_better = entry["greater_is_better"]
        needs_proba = entry["needs_proba"]
        fn = _FEVAL_REGISTRY.get(name)
        if fn is None:
            log.warning("Unknown feval metric: %s — skipping", name)
            continue

        # Build display name
        if params:
            parts = ", ".join(f"{k}={v}" for k, v in sorted(params.items()))
            display = f"{name} ({parts})"
        else:
            display = name

        def _make_feval(
            _fn=fn, _name=display, _gib=greater_is_better,
            _needs_proba=needs_proba, _params=params, _task=task,
        ):
            def feval(y_pred, dataset):
                y_true = dataset.get_label()
                if _task == "binary":
                    proba = _sigmoid(y_pred)
                elif _task == "multiclass":
                    num_class = CFG["lgbm_params"].get("num_class", 2)
                    proba = y_pred.reshape(-1, num_class)
                    proba = _softmax(proba)
                else:
                    proba = y_pred
                # For metrics that don't need probabilities, convert to labels
                if not _needs_proba and _task in ("binary", "multiclass"):
                    if proba.ndim == 2:
                        pred = proba.argmax(axis=1).astype(np.int64)
                    else:
                        pred = (proba >= 0.5).astype(np.int64)
                else:
                    pred = proba
                value = _fn(np.asarray(y_true), np.asarray(pred), **_params)
                return (_name, value, _gib)
            return feval

        fevals.append(_make_feval())

    return fevals


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  CV split reproduction (mirrors the model's split.method; #228)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
#  The calibration OOF must respect the same time/group boundary the model
#  was trained with; a shuffled K-fold would leak across it on retrain.
#  These helpers rebuild the outer folds from config.json["split"] using the
#  same logic as LizyML (sklearn for the standard families, ported numpy for
#  purged / group-time-series / blocked-group). Rows are sorted the same way
#  (by time_col, or blocks.col) before splitting; returned indices are mapped
#  back to the input row order.

def _kfold_folds(n, y, method, shuffle, random_state, n_splits):
    cls = StratifiedKFold if method == "stratified_kfold" else KFold
    kf = cls(
        n_splits=n_splits, shuffle=shuffle,
        random_state=random_state if shuffle else None,
    )
    return list(kf.split(np.arange(n), y))


def _purged_ts_folds(n, n_splits, purge_gap, embargo, max_train, max_test):
    idx = np.arange(n)
    fold_size = n // (n_splits + 1)
    if fold_size == 0:
        raise ValueError(f"n_samples={n} too small for n_splits={n_splits}")
    folds = []
    for k in range(n_splits):
        valid_start = (k + 1) * fold_size
        valid_end = min((k + 2) * fold_size, n)
        if valid_start >= valid_end:
            continue
        train_end = (k + 1) * fold_size - purge_gap - embargo
        if train_end <= 0:
            continue
        tr = idx[:train_end]
        va = idx[valid_start:valid_end]
        if max_train is not None:
            tr = tr[-max_train:]
        if max_test is not None:
            va = va[:max_test]
        folds.append((tr, va))
    return folds


def _group_ts_folds(groups, n_splits, gap, max_train, max_test):
    groups = np.asarray(groups)
    _, first_idx = np.unique(groups, return_index=True)
    ordered_unique = groups[np.sort(first_idx)]
    n_groups = len(ordered_unique)
    if n_groups < n_splits + 1 + gap:
        raise ValueError(
            f"Not enough groups ({n_groups}) for n_splits={n_splits} gap={gap}"
        )
    gfs = n_groups // (n_splits + 1)
    folds = []
    for k in range(n_splits):
        train_group_end = (k + 1) * gfs
        valid_group_start = train_group_end + gap
        if k == n_splits - 1:
            valid_group_end = n_groups
        else:
            valid_group_end = min(valid_group_start + gfs, n_groups)
        if valid_group_start >= valid_group_end:
            continue
        tgl = ordered_unique[:train_group_end]
        vgl = ordered_unique[valid_group_start:valid_group_end]
        if max_train is not None:
            tgl = tgl[-max_train:]
        if max_test is not None:
            vgl = vgl[:max_test]
        tr = np.where(np.isin(groups, list(set(tgl))))[0]
        va = np.where(np.isin(groups, list(set(vgl))))[0]
        folds.append((tr, va))
    return folds


def _blocked_period_masks(bv, cutoffs):
    masks = [bv < cutoffs[0]]
    for i in range(1, len(cutoffs)):
        masks.append((bv >= cutoffs[i - 1]) & (bv < cutoffs[i]))
    masks.append(bv >= cutoffs[-1])
    return masks


def _blocked_split_users(all_users, y, groups, sp):
    gp = sp["groups"]
    n_splits = gp["n_splits"]
    stratify = gp["stratify"]
    shuffle = gp["shuffle"]
    rng = np.random.RandomState(sp["random_state"])
    nu = len(all_users)
    if stratify and y is not None:
        labels = np.empty(nu, dtype=y.dtype)
        for i, u in enumerate(all_users):
            uy = y[groups == u]
            vals, cnts = np.unique(uy, return_counts=True)
            labels[i] = vals[cnts.argmax()]
        per_class = []
        for cls in np.unique(labels):
            ci = np.where(labels == cls)[0]
            if shuffle:
                rng.shuffle(ci)
            per_class.append(ci)
        order = []
        max_len = max(len(c) for c in per_class)
        for i in range(max_len):
            for ci in per_class:
                if i < len(ci):
                    order.append(int(ci[i]))
        user_order = np.array(order, dtype=np.intp)
    elif shuffle:
        user_order = rng.permutation(nu)
    else:
        user_order = np.arange(nu)
    fold_sizes = np.full(n_splits, nu // n_splits, dtype=int)
    fold_sizes[: nu % n_splits] += 1
    out = []
    cur = 0
    for k in range(n_splits):
        vi = user_order[cur : cur + fold_sizes[k]]
        ti = np.concatenate([user_order[:cur], user_order[cur + fold_sizes[k] :]])
        out.append((all_users[ti], all_users[vi]))
        cur += fold_sizes[k]
    return out


def _blocked_group_folds(block_values, groups, y, sp):
    bl = sp["blocks"]
    cutoffs = sorted(bl["cutoffs"])
    mode = bl["mode"]
    train_window = bl.get("train_window")
    min_train = sp.get("min_train_rows", 1)
    min_valid = sp.get("min_valid_rows", 1)
    bv = np.asarray(block_values)
    n = len(bv)
    masks = _blocked_period_masks(bv, cutoffs)
    folds = []
    for t in range(len(cutoffs)):
        train_mask = np.zeros(n, dtype=bool)
        valid_mask = masks[t + 1]
        if mode == "expanding":
            for i in range(t + 1):
                train_mask |= masks[i]
        else:
            if train_window is None:
                raise ValueError("train_window must be set when mode='sliding'")
            for i in range(max(0, t + 1 - train_window), t + 1):
                train_mask |= masks[i]
        tpi = np.where(train_mask)[0]
        vpi = np.where(valid_mask)[0]
        if len(tpi) == 0 or len(vpi) == 0:
            continue
        all_users = np.unique(np.concatenate([groups[tpi], groups[vpi]]))
        for tu, vu in _blocked_split_users(all_users, y, groups, sp):
            tr = tpi[np.isin(groups[tpi], list(set(tu)))]
            va = vpi[np.isin(groups[vpi], list(set(vu)))]
            if len(tr) < min_train or len(va) < min_valid:
                continue
            folds.append((tr.astype(np.intp), va.astype(np.intp)))
    return folds


def _resolve_folds(df: pd.DataFrame, y: np.ndarray):
    """Return outer CV ``(train_idx, valid_idx)`` pairs in ``df`` row order,
    reproducing the model's ``split.method`` so the calibration OOF respects
    the same boundary. Falls back to shuffled K-fold for older exports that
    have no ``split`` block."""
    sp = CFG.get("split")
    n = len(y)
    seed = CFG["seed"]
    task = CFG["_task"]
    if not sp:
        # Legacy export (no split block): the original task-based shuffled
        # K-fold, preserved for back-compat.
        cls = StratifiedKFold if task == "binary" else KFold
        return list(
            cls(
                n_splits=CFG.get("calibration_n_splits", 5),
                shuffle=True, random_state=seed,
            ).split(np.arange(n), y)
        )

    method = sp["method"]
    n_splits = sp["n_splits"]
    if method in ("kfold", "stratified_kfold"):
        return _kfold_folds(
            n, y, method, sp.get("shuffle", True),
            sp.get("random_state", seed), n_splits,
        )

    if method in ("time_series", "purged_time_series", "group_time_series"):
        order = np.asarray(df[sp["time_col"]].argsort())
    elif method == "blocked_group_kfold":
        order = np.asarray(df[sp["blocks"]["col"]].argsort())
    else:  # group_kfold / stratified_group_kfold — no reordering
        order = np.arange(n)

    y_s = np.asarray(y)[order]
    groups_s = None
    if sp.get("group_col"):
        groups_s = df[sp["group_col"]].to_numpy()[order]

    if method == "time_series":
        tss = TimeSeriesSplit(
            n_splits=n_splits, gap=sp.get("gap", 0),
            max_train_size=sp.get("train_size_max"),
            test_size=sp.get("test_size_max"),
        )
        folds = list(tss.split(np.arange(n)))
    elif method == "purged_time_series":
        folds = _purged_ts_folds(
            n, n_splits, sp.get("purge_gap", 0), sp.get("embargo", 0),
            sp.get("train_size_max"), sp.get("test_size_max"),
        )
    elif method == "group_time_series":
        folds = _group_ts_folds(
            groups_s, n_splits, sp.get("gap", 0),
            sp.get("train_size_max"), sp.get("test_size_max"),
        )
    elif method == "group_kfold":
        folds = list(GroupKFold(n_splits=n_splits).split(np.arange(n), y_s, groups_s))
    elif method == "stratified_group_kfold":
        sgkf = StratifiedGroupKFold(
            n_splits=n_splits, shuffle=sp["shuffle"],
            random_state=sp["random_state"] if sp["shuffle"] else None,
        )
        folds = list(sgkf.split(np.arange(n), y_s, groups_s))
    elif method == "blocked_group_kfold":
        bv = df[sp["blocks"]["col"]].to_numpy()[order]
        gv = df[sp["groups"]["col"]].to_numpy()[order]
        folds = _blocked_group_folds(bv, gv, y_s, sp)
    else:
        raise ValueError(f"Unsupported split.method for retrain: {method!r}")

    return [(order[np.asarray(tr)], order[np.asarray(va)]) for tr, va in folds]


def _generate_oof(X: np.ndarray, y: np.ndarray, folds) -> np.ndarray:
    """Lightweight CV to produce OOF raw scores (logits) over *folds*."""
    oof = np.full(len(y), np.nan)
    n_folds = len(folds)
    for i, (trn, val) in enumerate(folds):
        log.info("    CV fold %d/%d", i + 1, n_folds)
        ds = lgb.Dataset(X[trn], label=y[trn])
        bst = lgb.train(CFG["lgbm_params"], ds,
                        num_boost_round=CFG["num_boost_round"],
                        callbacks=[lgb.log_evaluation(0)])
        oof[val] = bst.predict(X[val], raw_score=True)
    return oof


def _fit_platt(scores: np.ndarray, y: np.ndarray) -> dict:
    lr = LogisticRegression(C=1.0, solver="lbfgs", max_iter=200)
    lr.fit(scores.reshape(-1, 1), y)
    return {"method": "platt",
            "a": float(lr.coef_[0, 0]), "b": float(lr.intercept_[0])}


def _fit_beta(scores: np.ndarray, y: np.ndarray) -> dict:
    from scipy.optimize import minimize
    s = np.clip(_sigmoid(scores), 1e-10, 1 - 1e-10)
    yf = y.astype(float)
    ls, l1s = np.log(s), np.log(1 - s)

    def nll(p):
        prob = np.clip(_sigmoid(p[0] * ls + p[1] * l1s + p[2]), 1e-10, 1 - 1e-10)
        return float(-np.sum(yf * np.log(prob) + (1 - yf) * np.log(1 - prob)))

    r = minimize(nll, x0=[1, 1, 0], method="L-BFGS-B")
    return {"method": "beta",
            "a": float(r.x[0]), "b": float(r.x[1]), "c": float(r.x[2])}


def _fit_isotonic(scores: np.ndarray, y: np.ndarray) -> dict:
    n = len(scores)
    params = {
        "objective": "binary", "metric": "binary_logloss",
        "monotone_constraints": [1], "monotone_constraints_method": "advanced",
        "num_leaves": 7, "max_depth": 3, "learning_rate": 0.03,
        "lambda_l2": 5.0, "min_data_in_leaf": max(1, math.ceil(n * 0.01)),
        "verbose": -1, "seed": CFG["seed"],
    }
    rng = np.random.default_rng(CFG["seed"])
    n_val = max(1, int(n * 0.1))
    idx = rng.permutation(n)
    X_cal = scores.reshape(-1, 1)

    ds_t = lgb.Dataset(X_cal[idx[n_val:]], label=y[idx[n_val:]].astype(float))
    ds_v = lgb.Dataset(X_cal[idx[:n_val]], label=y[idx[:n_val]].astype(float),
                       reference=ds_t)
    bst = lgb.train(params, ds_t, num_boost_round=1000,
                    valid_sets=[ds_v], valid_names=["valid"],
                    callbacks=[lgb.early_stopping(100, verbose=False),
                               lgb.log_evaluation(0)])
    bst.save_model(str(ARTIFACTS / "calibrator_model.txt"))
    return {"method": "isotonic", "model_file": "calibrator_model.txt"}


_CAL_FITTERS = {"platt": _fit_platt, "beta": _fit_beta, "isotonic": _fit_isotonic}


def fit_calibrator(X: np.ndarray, y: np.ndarray, df: pd.DataFrame) -> dict | None:
    """Generate OOF scores and fit calibrator. Returns params or None."""
    method = CFG.get("calibration_method")
    if not method or CFG["_task"] != "binary":
        return None

    log.info("[3/4] Generating OOF scores ...")
    folds = _resolve_folds(df, y)
    oof = _generate_oof(X, y, folds)

    log.info("[4/4] Fitting %s calibrator ...", method)
    if method not in _CAL_FITTERS:
        raise ValueError(
            f"Unknown calibration method: {method!r}. "
            f"Supported: {list(_CAL_FITTERS)}"
        )
    # A time/group split can leave first-period / uncovered rows out of every
    # validation fold, so their OOF score stays NaN. Fit the calibrator on the
    # covered rows only (matches LizyML's cross-fit C_final; #228).
    covered = ~np.isnan(oof)
    params = _CAL_FITTERS[method](oof[covered], y[covered])
    with open(ARTIFACTS / "calibrator.json", "w", encoding="utf-8") as f:
        json.dump(params, f, indent=2)
    log.info("    saved calibrator.json")
    return params


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Main
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _encode_target(y: pd.Series) -> pd.Series:
    """Map non-numeric target labels to int codes (H-0070)."""
    enc = CFG.get("target_encoder", {})
    if not enc.get("needs_encoding"):
        return y
    classes = enc["classes"]
    mapping = {c: i for i, c in enumerate(classes)}
    unseen = set(pd.Series(y).dropna().unique()) - mapping.keys()
    if unseen:
        raise ValueError(
            f"Target column contains labels not seen at fit time: "
            f"{sorted(unseen, key=str)}. Known: {classes}"
        )
    return pd.Series(y).map(mapping).astype(np.int64)


def train(df: pd.DataFrame, *, calibrate: bool = True) -> None:
    target = CFG["_target_col"]
    y = _encode_target(df[target])
    X_raw = df.drop(columns=[target])

    log.info("[1/4] Fitting feature pipeline ...")
    state = fit_pipeline(X_raw)
    X = transform(X_raw, state)

    log.info("[2/4] Training LightGBM ...")
    cat_cols = [c for c in CFG["categorical_features"] if c in X.columns]
    train_lgbm(X, y, cat_cols)

    if calibrate:
        fit_calibrator(X.values, y.values, df)
    else:
        log.info("[3/4] Calibration skipped")
        log.info("[4/4] --")

    log.info("Done.")


def main() -> None:
    p = argparse.ArgumentParser(description="Train LightGBM (LizyML codegen)")
    p.add_argument("data", help="CSV or Parquet file")
    p.add_argument("--no-calibration", action="store_true")
    args = p.parse_args()

    path = Path(args.data)
    df = pd.read_parquet(path) if path.suffix == ".parquet" else pd.read_csv(path)

    target = CFG["_target_col"]
    if target not in df.columns:
        log.error(\'Target "%s" not found. Columns: %s\', target, list(df.columns))
        sys.exit(1)

    train(df, calibrate=not args.no_calibration)


if __name__ == "__main__":
    main()
'''

_PREDICT_PY = '''\
#!/usr/bin/env python3
"""Run inference with a trained model.

Usage:
    python predict.py test_data.csv
    python predict.py test_data.csv -o predictions.csv

Generated by lizyml -- https://github.com/nbx-liz/LizyML
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s  %(message)s", datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

ROOT = Path(__file__).parent
ARTIFACTS = ROOT / "artifacts"

with open(ROOT / "config.json", encoding="utf-8") as _f:
    CFG = json.load(_f)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Feature Transform (predict-time: no re-fitting)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _load_pipeline() -> dict:
    path = ARTIFACTS / "pipeline_state.json"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found. Run train.py first.")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def transform(df: pd.DataFrame) -> pd.DataFrame:
    """Select expected columns and apply categorical encoding."""
    state = _load_pipeline()
    expected = state["feature_names"]

    missing = sorted(set(expected) - set(df.columns))
    if missing:
        raise ValueError(
            f"Missing {len(missing)} column(s): {missing}. "
            f"Expected: {expected}"
        )

    extra = sorted(set(df.columns) - set(expected))
    if extra:
        log.warning("Ignoring %d extra column(s): %s", len(extra), extra)

    X = df[expected].copy()
    policy = state.get("unseen_policy", "nan")
    unseen_codes = state.get("unseen_codes", {})
    for col, mapping in state.get("category_mappings", {}).items():
        if col in X.columns:
            codes = X[col].astype(str).map(mapping)  # unseen -> NaN
            if policy == "mode" and col in unseen_codes:
                # Match the runtime encoder: replace unseen with the training mode.
                codes = codes.fillna(unseen_codes[col])
            elif policy == "error" and codes.isna().any():
                raise ValueError(
                    f"Column '{col}' contains unseen categories "
                    "(unseen_policy='error')"
                )
            X[col] = codes
    return X


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Calibration (apply only)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _sigmoid(x: np.ndarray) -> np.ndarray:
    return np.where(x >= 0, 1 / (1 + np.exp(-x)), np.exp(x) / (1 + np.exp(x)))


def _load_calibrator() -> dict | None:
    path = ARTIFACTS / "calibrator.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def calibrate(raw_scores: np.ndarray, cal: dict) -> np.ndarray:
    """Map raw logits -> calibrated probabilities."""
    m = cal["method"]
    if m == "platt":
        return 1 / (1 + np.exp(-(cal["a"] * raw_scores + cal["b"])))
    if m == "beta":
        s = np.clip(_sigmoid(raw_scores), 1e-10, 1 - 1e-10)
        logit = cal["a"] * np.log(s) + cal["b"] * np.log(1 - s) + cal["c"]
        return np.clip(_sigmoid(logit), 0, 1)
    if m == "isotonic":
        model_file = Path(cal["model_file"]).name  # sanitize path
        bst = lgb.Booster(model_file=str(ARTIFACTS / model_file))
        return np.clip(bst.predict(raw_scores.reshape(-1, 1)), 0, 1)
    raise ValueError(
        f\'Unknown calibration method: "{m}". \'
        "Supported: platt, beta, isotonic"
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Predict
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _decode_pred(codes: np.ndarray) -> np.ndarray:
    """Map int codes back to original labels (H-0070). No-op when numeric."""
    enc = CFG.get("target_encoder", {})
    if not enc.get("needs_encoding"):
        return codes
    classes = enc["classes"]
    return np.array([classes[int(c)] for c in codes], dtype=object)


def predict(df: pd.DataFrame) -> dict[str, np.ndarray | None]:
    """Run inference. Returns {"pred": ..., "proba": ...}."""
    # Feed a numpy array (not a DataFrame) so LightGBM matches features
    # positionally by ``feature_names`` order.  Categorical columns are already
    # integer-coded by ``transform`` (matching the training category codes);
    # passing a DataFrame would trip LightGBM's pandas-categorical dtype check.
    X = transform(df).to_numpy()
    booster = lgb.Booster(model_file=str(ARTIFACTS / "model.txt"))
    task = CFG["_task"]

    if task == "regression":
        return {"pred": np.asarray(booster.predict(X), dtype=np.float64),
                "proba": None}

    if task == "binary":
        proba = np.asarray(booster.predict(X), dtype=np.float64)
        cal = _load_calibrator()
        if cal:
            logits = np.asarray(booster.predict(X, raw_score=True), dtype=np.float64)
            proba = calibrate(logits, cal)
        codes = (proba > 0.5).astype(np.int64)
        return {"pred": _decode_pred(codes), "proba": proba}

    if task == "multiclass":
        proba = np.asarray(booster.predict(X), dtype=np.float64)
        codes = np.argmax(proba, axis=1).astype(np.int64)
        return {"pred": _decode_pred(codes), "proba": proba}

    raise ValueError(f\'Unknown task: "{task}"\')


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main() -> None:
    p = argparse.ArgumentParser(description="Predict (LizyML codegen)")
    p.add_argument("data", help="CSV or Parquet file")
    p.add_argument("-o", "--output", default="predictions.csv")
    args = p.parse_args()

    path = Path(args.data)
    df = pd.read_parquet(path) if path.suffix == ".parquet" else pd.read_csv(path)
    result = predict(df)

    out = pd.DataFrame({"pred": result["pred"]})
    if result["proba"] is not None:
        if result["proba"].ndim == 1:
            out["proba"] = result["proba"]
        else:
            for i in range(result["proba"].shape[1]):
                out[f"proba_{i}"] = result["proba"][:, i]
    out.to_csv(args.output, index=False)
    log.info("Saved %d rows -> %s", len(out), args.output)


if __name__ == "__main__":
    main()
'''

_TEST_EQUIVALENCE_PY = '''\
#!/usr/bin/env python3
"""Verify that codegen predictions match a LizyML reference.

Usage:
    python test_equivalence.py test_data.csv --reference reference_predictions.csv

Compares the output of predict.py against a reference CSV exported from
LizyML (``Model.predict()``).  The reference file must contain a ``pred``
column and optionally a ``proba`` column.

This checker imports ``predict`` and calls ``predict.predict()`` directly, so
it exercises the exact code path users run.  It never re-implements the
transform / calibration logic (a second copy would let the two paths drift
apart silently).

Generated by lizyml -- https://github.com/nbx-liz/LizyML
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd

import predict

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s  %(message)s", datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Equivalence check
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _compare(
    name: str, actual: np.ndarray, expected: np.ndarray, rtol: float
) -> bool:
    """Compare two arrays and log result."""
    if len(actual) != len(expected):
        log.error(
            "%s: FAIL — row count mismatch (codegen=%d, ref=%d)",
            name, len(actual), len(expected),
        )
        return False
    try:
        np.testing.assert_allclose(actual, expected, rtol=rtol)
        log.info("%s: PASS (rtol=%s, n=%d)", name, rtol, len(actual))
        return True
    except AssertionError as e:
        log.error("%s: FAIL\\n%s", name, e)
        return False


def check_equivalence(
    df: pd.DataFrame,
    ref: pd.DataFrame,
    *,
    rtol: float = 1e-7,
) -> bool:
    """Compare codegen predictions against reference."""
    if "pred" not in ref.columns:
        raise ValueError(
            \'"pred" column not found in reference file. \'
            f"Available columns: {list(ref.columns)}"
        )

    result = predict.predict(df)
    ok = True

    # Check pred
    if not _compare("pred", result["pred"], ref["pred"].values, rtol):
        ok = False

    # Check proba
    proba = result["proba"]
    if proba is not None:
        if proba.ndim == 1 and "proba" in ref.columns:
            # Binary: single proba column
            if not _compare("proba", proba, ref["proba"].values, rtol):
                ok = False
        elif proba.ndim == 2:
            # Multiclass: proba_0, proba_1, ...
            for i in range(proba.shape[1]):
                col = f"proba_{i}"
                if col in ref.columns:
                    if not _compare(col, proba[:, i], ref[col].values, rtol):
                        ok = False

    return ok


def main() -> None:
    p = argparse.ArgumentParser(
        description="Verify codegen predictions match LizyML reference"
    )
    p.add_argument("data", help="CSV or Parquet input data")
    p.add_argument("--reference", "-r", required=True,
                   help="Reference predictions CSV (from LizyML)")
    p.add_argument("--rtol", type=float, default=1e-7,
                   help="Relative tolerance (default: 1e-7)")
    args = p.parse_args()

    data_path = Path(args.data)
    df = (pd.read_parquet(data_path) if data_path.suffix == ".parquet"
          else pd.read_csv(data_path))
    ref = pd.read_csv(args.reference)

    ok = check_equivalence(df, ref, rtol=args.rtol)
    if ok:
        log.info("All checks PASSED.")
    else:
        log.error("Some checks FAILED.")
        sys.exit(1)


if __name__ == "__main__":
    main()
'''

_REQUIREMENTS_BASE = """\
lightgbm>=4.0
numpy
pandas
scikit-learn
"""


def render_train_py() -> str:
    """Return the train.py source code."""
    return _TRAIN_PY


def render_predict_py() -> str:
    """Return the predict.py source code."""
    return _PREDICT_PY


def render_requirements_txt(*, uses_beta_calibration: bool = False) -> str:
    """Return the requirements.txt content.

    ``scipy`` is pinned only when the model uses beta calibration -- the sole
    generated code path that imports it (lazily, inside ``_fit_beta`` in
    ``train.py``; the predict-time beta application is pure numpy). This keeps
    the emitted dependency set matching the README claim (#218).
    """
    if uses_beta_calibration:
        return _REQUIREMENTS_BASE + "scipy\n"
    return _REQUIREMENTS_BASE


def render_test_equivalence_py() -> str:
    """Return the test_equivalence.py source code."""
    return _TEST_EQUIVALENCE_PY
